// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbmS6aGSKQGZfz4rZIKn48jMbJs3054NQ',
    appId: '1:28653808379:web:44c967f5a749d7776e5e5e',
    messagingSenderId: '28653808379',
    projectId: 'social-dce70',
    authDomain: 'social-dce70.firebaseapp.com',
    storageBucket: 'social-dce70.appspot.com',
    measurementId: 'G-MCHDC73WE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK7LK_XjI_SJPU3dkR0t0FFAiCUOHXZHY',
    appId: '1:28653808379:android:2183718fd82753986e5e5e',
    messagingSenderId: '28653808379',
    projectId: 'social-dce70',
    storageBucket: 'social-dce70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyfXTJSysCnRum-5BvOiyO8uArf5DinlA',
    appId: '1:28653808379:ios:18de9110acf6f27d6e5e5e',
    messagingSenderId: '28653808379',
    projectId: 'social-dce70',
    storageBucket: 'social-dce70.appspot.com',
    iosBundleId: 'com.chironjit.social',
  );
}
